"""initial schema

Revision ID: 8e73364503ec
Revises: 
Create Date: 2026-07-24 11:08:43.991794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e73364503ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aeronaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('capacidade_maxima', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('passageiros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('documento', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento')
    )
    op.create_table('terminais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('nacional', 'internacional', name='tipo_terminal'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('terminal_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('livre', 'ocupado', name='status_gate'), nullable=False),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('terminal_id', 'codigo')
    )
    op.create_table('voos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_voo', sa.String(length=10), nullable=False),
    sa.Column('origem', sa.String(length=100), nullable=False),
    sa.Column('destino', sa.String(length=100), nullable=False),
    sa.Column('horario_previsto_chegada', sa.DateTime(), nullable=True),
    sa.Column('horario_previsto_partida', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('no_horario', 'atrasado', 'embarcando', 'finalizado', 'cancelado', name='status_voo'), nullable=False),
    sa.Column('aeronave_id', sa.Integer(), nullable=False),
    sa.Column('terminal_id', sa.Integer(), nullable=False),
    sa.Column('gate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aeronave_id'], ['aeronaves.id'], ),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_voo')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passageiro_id', sa.Integer(), nullable=False),
    sa.Column('voo_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('confirmado', 'checkin_feito', 'embarcado', 'perdeu_voo', 'realocado', name='status_reserva'), nullable=False),
    sa.Column('assento', sa.String(length=5), nullable=True),
    sa.Column('realocado_de_reserva_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['passageiro_id'], ['passageiros.id'], ),
    sa.ForeignKeyConstraint(['realocado_de_reserva_id'], ['reservas.id'], ),
    sa.ForeignKeyConstraint(['voo_id'], ['voos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passageiro_id', 'voo_id')
    )
    op.create_table('malas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_identificacao', sa.String(length=30), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('despachada', 'em_triagem', 'carregada', 'extraviada', 'entregue', name='status_mala'), nullable=False),
    sa.Column('localizacao_atual', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_identificacao')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('malas')
    op.drop_table('reservas')
    op.drop_table('voos')
    op.drop_table('gates')
    op.drop_table('terminais')
    op.drop_table('passageiros')
    op.drop_table('aeronaves')
    # ### end Alembic commands ###
